// Generated by Wrangler on Mon Jul 15 2024 19:59:47 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  zed_themes: KVNamespace;
  zed_shares: KVNamespace;
  zed_options: KVNamespace;
}
