// Generated by Wrangler on Sun Aug 18 2024 19:13:11 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  zed_shares: KVNamespace;
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
  db: D1Database;
}
