// Generated by Wrangler on Wed Sep 25 2024 19:48:45 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  zed_shares: KVNamespace;
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
  SENTRY_AUTH_TOKEN: string;
  db: D1Database;
}
